# Generated by Django 5.2.5 on 2025-08-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='unicode',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='sub_column',
            new_name='sub_course',
        ),
    ]
