# Generated by Django 5.2.3 on 2025-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_column',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
