# Generated by Django 5.2.1 on 2025-08-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sub_course',
        ),
    ]
