# Generated by Django 5.2.5 on 2025-08-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_unicode_course_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sub_course',
            new_name='sub_column',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='unicode',
        ),
    ]
