# Generated by Django 5.2.3 on 2025-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_name_alter_course_sub_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('IT', 'IT'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Business', 'Business'), ('Arts', 'Arts'), ('Science', 'Science'), ('Accounting', 'Accounting')], max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_column',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Networking', 'Networking'), ('Cyber Security', 'Cyber Security'), ('Computer Science Engineering (CSE)', 'Computer Science Engineering (CSE)'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('MBBS (Bachelor of Medicine & Bachelor of Surgery)', 'MBBS (Bachelor of Medicine & Bachelor of Surgery)'), ('BDS (Bachelor of Dental Surgery)', 'BDS (Bachelor of Dental Surgery)'), ('BAMS (Ayurveda)', 'BAMS (Ayurveda)'), ('BHMS (Homeopathy)', 'BHMS (Homeopathy)'), ('Accounting', 'Accounting'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources'), ('Painting', 'Painting'), ('Music', 'Music'), ('Dance', 'Dance'), ('Literature', 'Literature'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Mathematics', 'Mathematics'), ('CA', 'CA'), ('ACCA', 'ACCA'), ('CMA', 'CMA')], max_length=255),
        ),
    ]
