# Generated by Django 5.2.5 on 2025-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_sub_course_course_sub_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unicode', models.CharField(editable=False, max_length=10, unique=True)),
                ('sub_courses', models.JSONField(default=list)),
            ],
        ),
    ]
