# Generated by Django 5.2.5 on 2025-08-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursetype'),
        ('course', '0005_alter_course_name_alter_course_sub_column'),
    ]

    operations = [
    ]
