# Generated by Django 5.2.5 on 2025-08-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_20250809_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
