# Generated by Django 5.2.4 on 2025-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern')], max_length=10)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations')], max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
