# Generated by Django 5.2.4 on 2025-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_options_staff_created_at_and_more'),
        ('staff', '0003_alter_staff_status'),
    ]

    operations = [
    ]
