# Generated by Django 5.2.4 on 2025-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workassignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
