# Generated by Django 5.2.4 on 2025-08-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('workassignment', '0002_workassignment_delete_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
