# Generated by Django 5.2.4 on 2025-08-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_staff_code_alter_staff_gender'),
        ('workassignment', '0003_alter_workassignment_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workassignment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='task_title',
            field=models.CharField(max_length=200),
        ),
    ]
