# Generated by Django 5.2.3 on 2025-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workassignment', '0004_remove_workassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
