# Generated by Django 5.2.4 on 2025-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workassignment', '0005_workassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
