# Generated by Django 5.2.3 on 2025-08-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('workassignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='staff.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='workassignment.workassignment')),
            ],
        ),
    ]
