# Generated by Django 5.2.4 on 2025-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='daily_task',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
