# Generated by Django 5.2.4 on 2025-08-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_daily_task'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('staff_code', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='daily_task',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendence_details', to='staff.staff'),
        ),
    ]
