# Generated by Django 5.2.4 on 2025-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_daily_task_remove_attendance_daily_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
